#!/bin/sh

# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

mount_no_mtd() {
    echo "- Mount no mtd -"
    mtd unlock rootfs || true
    if [ -b  /dev/root ] ; then
        mount -o remount,rw /dev/root /
    else
	[ -z "${rootfs}" ] && rootfs=`sed -ne 's/.*root=\([^[:space:]]\+\).*/\1/p' /proc/cmdline`

	if [ -n "${rootfs}" ] ; then
	    if [ -b ${rootfs} ] ; then
		mount -o remount,rw ${rootfs} /
	    else
		echo "Unable to mount ${rootfs}"
	    fi
	fi
    fi
}

check_for_mtd() {
    check_skip || {
	grep -qs rootfs_data /proc/mtd || {
	    mount_no_mtd && pi_mount_skip_next=true
	}
    }
}

boot_hook_add preinit_mount_root check_for_mtd

